-- MySQL Script generated by MySQL Workbench
-- Wed May  8 09:51:37 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema grade_book
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `grade_book` ;

-- -----------------------------------------------------
-- Schema grade_book
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `grade_book` DEFAULT CHARACTER SET utf8 ;
USE `grade_book` ;

-- -----------------------------------------------------
-- Table `grade_book`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grade_book`.`user` ;

CREATE TABLE IF NOT EXISTS `grade_book`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(45) NOT NULL,
  `role` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grade_book`.`teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grade_book`.`teacher` ;

CREATE TABLE IF NOT EXISTS `grade_book`.`teacher` (
  `teacher_id` INT NOT NULL AUTO_INCREMENT,
  `user_id_fk` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `phone_number` INT NOT NULL,
  PRIMARY KEY (`teacher_id`),
  INDEX `teacher_user_id_fk_idx` (`user_id_fk` ASC),
  CONSTRAINT `teacher_user_id_fk`
    FOREIGN KEY (`user_id_fk`)
    REFERENCES `grade_book`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grade_book`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grade_book`.`admin` ;

CREATE TABLE IF NOT EXISTS `grade_book`.`admin` (
  `admin_id` INT NOT NULL AUTO_INCREMENT,
  `user_id_fk` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`admin_id`),
  INDEX `admin_user_id_fk_idx` (`user_id_fk` ASC),
  CONSTRAINT `admin_user_id_fk`
    FOREIGN KEY (`user_id_fk`)
    REFERENCES `grade_book`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grade_book`.`grade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grade_book`.`grade` ;

CREATE TABLE IF NOT EXISTS `grade_book`.`grade` (
  `grade_id` INT NOT NULL AUTO_INCREMENT,
  `grade_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`grade_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grade_book`.`grades_taught`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grade_book`.`grades_taught` ;

CREATE TABLE IF NOT EXISTS `grade_book`.`grades_taught` (
  `grade_id_fk` INT NOT NULL,
  `teacher_id_fk` INT NOT NULL,
  PRIMARY KEY (`grade_id_fk`, `teacher_id_fk`),
  INDEX `teacher_id_fk_idx` (`teacher_id_fk` ASC),
  CONSTRAINT `gt_grade_id_fk`
    FOREIGN KEY (`grade_id_fk`)
    REFERENCES `grade_book`.`grade` (`grade_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `gt_teacher_id_fk`
    FOREIGN KEY (`teacher_id_fk`)
    REFERENCES `grade_book`.`teacher` (`teacher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grade_book`.`subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grade_book`.`subject` ;

CREATE TABLE IF NOT EXISTS `grade_book`.`subject` (
  `subject_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`subject_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grade_book`.`subjects_taught`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grade_book`.`subjects_taught` ;

CREATE TABLE IF NOT EXISTS `grade_book`.`subjects_taught` (
  `teacher_id_fk` INT NOT NULL,
  `subject_id_fk` INT NOT NULL,
  PRIMARY KEY (`teacher_id_fk`, `subject_id_fk`),
  INDEX `subject_id_fk_idx` (`subject_id_fk` ASC),
  CONSTRAINT `st_teacher_id_fk`
    FOREIGN KEY (`teacher_id_fk`)
    REFERENCES `grade_book`.`teacher` (`teacher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `st_subject_id_fk`
    FOREIGN KEY (`subject_id_fk`)
    REFERENCES `grade_book`.`subject` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grade_book`.`pupil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grade_book`.`pupil` ;

CREATE TABLE IF NOT EXISTS `grade_book`.`pupil` (
  `pupil_id` INT NOT NULL AUTO_INCREMENT,
  `grade_id_fk` INT NOT NULL,
  `user_id_fk` INT NOT NULL,
  `pupil_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pupil_id`),
  INDEX `grade_id_fk_idx` (`grade_id_fk` ASC),
  INDEX `user_id_fk_idx` (`user_id_fk` ASC),
  CONSTRAINT `p_grade_id_fk`
    FOREIGN KEY (`grade_id_fk`)
    REFERENCES `grade_book`.`grade` (`grade_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `p_user_id_fk`
    FOREIGN KEY (`user_id_fk`)
    REFERENCES `grade_book`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grade_book`.`marks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grade_book`.`marks` ;

CREATE TABLE IF NOT EXISTS `grade_book`.`marks` (
  `subject_id_fk` INT NOT NULL,
  `pupil_id_fk` INT NOT NULL,
  `percentage` INT NOT NULL,
  PRIMARY KEY (`subject_id_fk`, `pupil_id_fk`),
  INDEX `pupil_id_fk_idx` (`pupil_id_fk` ASC),
  CONSTRAINT `m_subject_id_fk`
    FOREIGN KEY (`subject_id_fk`)
    REFERENCES `grade_book`.`subject` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `m_pupil_id_fk`
    FOREIGN KEY (`pupil_id_fk`)
    REFERENCES `grade_book`.`pupil` (`pupil_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grade_book`.`grade_subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grade_book`.`grade_subject` ;

CREATE TABLE IF NOT EXISTS `grade_book`.`grade_subject` (
  `grade_id_fk` INT NOT NULL,
  `subject_id_fk` INT NOT NULL,
  PRIMARY KEY (`grade_id_fk`, `subject_id_fk`),
  INDEX `subject_id_fk_idx` (`subject_id_fk` ASC),
  CONSTRAINT `gs_grade_id_fk`
    FOREIGN KEY (`grade_id_fk`)
    REFERENCES `grade_book`.`grade` (`grade_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `gs_subject_id_fk`
    FOREIGN KEY (`subject_id_fk`)
    REFERENCES `grade_book`.`subject` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
